# Generated by Django 5.2.15 on 2026-09-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tupc_id', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sibol Graduation', max_length=150)),
                ('starts_at', models.DateTimeField()),
                ('venue', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_ceremony')],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ceremony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.ceremony'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='events.student'),
        ),
    ]
