# Generated by Django 5.2.15 on 2026-09-08 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_student_ceremony_ticket_ceremony_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=120)),
                ('relay', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Pulse sent'), ('uncertain', 'Needs inspection')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='events.ticket')),
            ],
        ),
    ]
