# Generated by Django 5.2.15 on 2026-09-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_gateadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='campus',
            field=models.CharField(choices=[('Cavite', 'Cavite'), ('Manila', 'Manila'), ('Taguig', 'Taguig'), ('Batangas', 'Batangas')], default='Manila', max_length=20),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
