# Generated by Django 5.2.15 on 2026-09-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_faculty_and_faculty_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Employee Faculty ID'),
        ),
        migrations.AlterField(
            model_name='gateadmission',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='events.ticket'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tupc_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='TUP ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('ADMIN', 'Admin account'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('GUEST', 'Guest')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='gateadmission',
            constraint=models.UniqueConstraint(fields=('ticket', 'relay'), name='one_admission_per_ticket_gate'),
        ),
    ]
