# Generated by Django 5.2.15 on 2026-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_faculty_employee_id_alter_gateadmission_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='roster_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
