# Generated by Django 5.2.15 on 2026-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ceremony_roster_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='access_code_digest',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
