# Generated by Django 5.2.15 on 2026-09-08 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_studentprofile_access_code_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='batch_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='commencement_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='theme',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
