# Generated by Django 5.2.15 on 2026-09-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_ceremony_batch_name_ceremony_commencement_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('registration', 'Registration'), ('awarding', 'Awarding'), ('song', 'Song'), ('video', 'Video'), ('speaker', 'Speaker'), ('speech', 'Speech'), ('assembly', 'Assembly'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(blank=True, max_length=200)),
                ('hymn_language', models.CharField(blank=True, choices=[('english', 'English'), ('tagalog', 'Tagalog')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.ceremony')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
    ]
