# Generated by Django 5.2.15 on 2026-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticket_guest_name_ticket_guest_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_access_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
