# Generated by Django 5.2.15 on 2026-09-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_studentprofile_current_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='approved', max_length=10),
        ),
    ]
