# Generated by Django 5.2.15 on 2026-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_ticket_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='current_access_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
