# Generated by Django 5.2.15 on 2026-09-08 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='program_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='archived_ceremony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_faculty', to='events.ceremony'),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_ceremony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_students', to='events.ceremony'),
        ),
    ]
