# Generated by Django 5.2.15 on 2026-09-09 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_guestreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gateadmission',
            name='one_admission_per_ticket_gate',
        ),
        migrations.AddField(
            model_name='gateadmission',
            name='direction',
            field=models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='gateadmission',
            constraint=models.UniqueConstraint(fields=('ticket', 'relay', 'direction'), name='one_admission_per_ticket_gate_direction'),
        ),
    ]
