# Generated by Django 5.2.15 on 2026-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_gateadmission_one_admission_per_ticket_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateadmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Pulse sent'), ('recorded', 'Recorded'), ('uncertain', 'Needs inspection')], default='pending', max_length=20),
        ),
    ]
