# Generated by Django 5.2.15 on 2026-09-11 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_gateadmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='auto_student_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='faculty_ticket_limit',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='student_ticket_limit',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='ticket_type',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('STUDENT', 'Student')], default='GUEST', max_length=10),
        ),
        migrations.AlterField(
            model_name='guestreservation',
            name='guest_relation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='guestreservation',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='receipts/'),
        ),
    ]
