# Generated by Django 5.2.15 on 2026-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_ceremony_auto_student_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='payment_qr',
            field=models.ImageField(blank=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='ticket_workflow',
            field=models.CharField(blank=True, choices=[('selling', 'Ticket selling'), ('requests', 'Request approval only')], default='', max_length=10),
        ),
    ]
