# Generated by Django 5.2.15 on 2026-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_ceremony_payment_qr_ceremony_ticket_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
